### ISSUE TITLE
Convert standalone chart from Vega-Lite to D3

### ISSUE THREAD

**Issue by ibnzterrell** [ibnzterrell/TwinPeaks#31]
To better support bespoke interaction code we should convert from Vega-Lite to D3 for standalone app

**Comment by magrawala** [comment]
I’m nbot sure this is necessary. Let’s talk about it next time we meet before embarking on it.

Maneesh

**Comment by ibnzterrell** [comment]
Ah just saw this  - I already did the conversion in  2d86236677ee2f364d75774be792b6a53a102f73. Closing as complete but we can talk about it in the next meet.
